trigger: none # will disable CI builds entirely

pr:
  - master

pool:
  vmImage: 'windows-2019'
  
steps:

- checkout: self
  clean: true
  lfs: false
  persistCredentials: false

- task: CmdLine@2
  displayName: yarn install
  inputs:
    script: yarn install

- task: CmdLine@2
  displayName: yarn run prepublishOnly
  inputs:
    script: yarn run prepublishOnly

- task: DownloadGitHubRelease@0
  inputs:
    connection: 'react-native-windows'
    userRepository: 'react-native-windows/CalculatorPackage'
    defaultVersionType: 'latest'
    downloadPath: '$(System.ArtifactsDirectory)'